---
extends:
  - "@nuxtjs"
  - plugin:prettier/recommended
plugins:
  - "@typescript-eslint"
parserOptions:
  parser: "@typescript-eslint/parser"
rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - args: all
      argsIgnorePattern: ^_
  no-unused-vars: off
  no-console: off
  camelcase: off
